---
## Adds the needed lines in the crontab file

- name: Add cron for checker
  cron:
    name: checker
    minute: "*/15"
    job: "/root/wordpress/checker.sh >> /tmp/checker.log 2>&1"

- name: Add cron for certificates
  cron:
    name: renewal
    minute: "0"
    hour: "4"
    weekday: "Thu,Mon"
    job: "/root/wordpress/cert_renewal.sh"
