---
# A Playbook to install Docker and Docker Compose on any viable remote host

- name: Install docker packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker

- name: Add Dockers official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify key with fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Set up stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker

- name: Update cache
  apt:
    update_cache: yes
  tags:
    - docker

- name: Install docker
  apt:
    name: docker-ce=18.03.*
    state: present
    update_cache: yes
  notify: Start docker on boot
  tags:
    - docker

- name: Create docker group
  group:
    name: docker
    state: present
  tags:
    - docker

- name: Add remote "ubuntu" user to "docker" group
  user:
    name: root
    group: docker
    append: yes
  tags:
    - docker

- name: Install docker-compose
  apt:
    name: docker-compose=1.8.*
    state: present
    update_cache: yes
  tags:
    - docker