---
# This is the main playbook with the whole flow for the wordpress website deploy with the needed configuration

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install dependencies
  include_tasks: dependencies.yml

- name: Network configuration
  include_tasks: network.yml

- name: Transfer Files
  include_tasks: files.yml

- name: Start container
  include_tasks: start_containers.yml

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes