---

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Setup docker
  include_tasks: install_docker.yml

- name: Setup files
  include_taks: transfer_files.yml

- name: Edit Cron File
  include_task: crontab.yml

# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system