---
# This Playbook starts all containers needed for the wordpress application using the docker-compose.yml

- name: Brings down existing containers if any
  docker_service:
    project_src: /root/wordpress
    state: absent

- name: Starts the containers
  docker_service:
    project_src: /root/wordpress
  register: output