---
# Transfer configuration files to remote host

- name: Create wordpress project directory
  file:
    path: /root/wordpress
    state: directory
    owner: root
    group: docker

- name: Create nginx  dir
  file:
    path: /root/wordpress/nginx-conf
    state: directory
    owner: root
    group: docker

- name: Copy nginx configuration file
  copy:
    src: nginx.conf
    dest: /root/wordpress/nginx-conf
    owner: root
    group: docker

- name: Copy ssl configuration file
  copy:
    src: options-ssl-nginx.conf
    dest: /root/wordpress/nginx-conf
    owner: root
    group: docker

- name: Copy compose file
  copy:
    src: docker-compose.yml
    dest: /root/wordpress
    owner: root
    group: docker

- name: Copy checker script
  copy:
    src: checker.sh
    dest: /root/wordpress
    owner: root
    group: docker

- name: Copy cert renewal script
  copy:
    src: cert_renewal.sh
    dest: /root/wordpress
    owner: root
    group: docker
    mode: 754

- name: Copy version file
  copy:
    src: version.txt
    dest: /root/wordpress
    owner: root
    group: docker