all:
  hosts:
    gig_test:
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_pass: [REDACTED]
      ansible_host: devopstest1.gigmedia.tech
      ansible_port: 22

    jenkins:
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_pass: [REDACTED]
      ansible_host: devopstest2.gigmedia.tech
      ansible_port: 22