---
# Creates necessary folders and transfers necessary files

- name: Ensure jenkins directory on docker host
  file:
    path: /root/jenkins
    state: directory
    owner: root
    group: docker
    mode: 0777

- name: Copy pipeline script to jenkins folder
  copy:
    src: pipeline.sh
    dest: /root/jenkins
    mode: 0777